# Generated by Django 2.0.6 on 2018-06-13 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_id', models.DateField()),
                ('content', models.CharField(max_length=500)),
                ('text_inside', models.BooleanField(default=False)),
            ],
        ),
    ]
