# Generated by Django 2.0.6 on 2018-06-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('diary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='text_inside',
        ),
    ]
