# Generated by Django 2.0.6 on 2018-06-20 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_auto_20180614_2312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='field',
            field=models.FileField(upload_to='media'),
        ),
    ]
